name: "Deploy hugo to GCS"
author: "Filip Chyla"
branding:
  icon: "upload-cloud"
  color: "green"
description: "Deploy a multi-config hugo based website to a Google Cloud Storage bucket"
inputs:
  deployment-target:
    description: "target of hugo deploy command, [[deployment.targets]].name"
    required: true
  deployment-environment:
    description: "build environment, which hugo configuration in config/ to use"
    required: true
  gcp-project-id:
    description: "google cloud project id, used to generate application credentials during runtime"
    required: true
  gcp-service-account-key:
    description: "service account key used for uploading to gcs"
    required: true
  gcp-create-credentials:
    description: "export default credentials, if used you must run actions/checkout@v3 before this action"
    required: true
runs:
  using: "composite"
  steps:
    # Login to gcloud and export credentials
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: ${{ inputs.gcp-project-id }}
        credentials_json: ${{ inputs.gcp-service-account-key }}
        create_credentials_file: ${{ inputs.gcp-create-credentials }}

    - name: Hugo setup
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: "0.136.0"

    - name: Build
      shell: bash
      run: hugo --minify --environment ${{ inputs.deployment-environment }}

    - name: Deploy
      shell: bash
      run: hugo deploy --target="${{ inputs.deployment-target }}" --environment ${{ inputs.deployment-environment }}
